# Generated by Django 5.0.6 on 2024-06-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', 'initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.CharField(max_length=2883),
        ),
    ]
